config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get '/login' => "customers/sessions#new"
  post '/login' => "customers/sessions#create"
  get '/dashboard' => "customers#dashboard"
  delete '/logout' => "customers/sessions#destroy", as: 'logout'
  # get '/checkout' => "checkout#checkout"

  scope '/admin' do
    root to: 'admins#show'
    get '/orders/:id' => "admins/orders#show", as: 'admin_order'
    put '/orders' => "admins/orders#update"
    get '/login' => "admins/sessions#new", as: 'admin_login'
    post '/login' => "admins/sessions#create"
    delete '/logout' => "admins/sessions#destroy", as: 'admin_logout'
    get '/dashboard' => "admins#show", as: 'admin_dashboard'
    get '/items' => "admins/items#index", as: 'admin_items'
    get '/items/:id/edit' => 'admins/items#edit', as: 'edit_admin_item'
  end
  resources :admins, only: [:edit, :update]

  resources :customers, only: [:new, :create]

  resources :items, only: [:index, :show]

  patch '/items/:id' => 'admins/items#update'
  get '/cart' => "carts#show", as: "cart"
  post '/cart' => "carts#update"
  delete '/cart' => "carts#destroy"

  get '/orders' => "customers/orders#index", as: 'customer_orders'
  get '/order' => "customers/orders#show"

  resources :checkouts do
    root to: 'checkouts#checkout'
  end
  resources :categories, :path => '', only: [:show]

  resources :carts, only: [:create]

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  validates :email, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :password_digest, presence: true

  has_many :orders

  def stripe_customer
    if stripe_id?
      Stripe::Customer.retrieve(stripe_id)
    else
      stripe_customer = Stripe::Customer.create(email: email)
      update(stripe_id: stripe_customer.id)
      stripe_customer
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  validates :total_price_in_cents, presence: true
  validates :status, presence: true
  validates :customer, presence: true
  validates :items, presence: true

  before_validation :set_total

  belongs_to :status
  belongs_to :customer
  has_many :order_items
  has_many :items, through: :order_items

  scope :most_recent, -> { order(:updated_at).reverse_order }

  def calculated_price_in_cents
    items_and_quantities.map do |item, quantity|
      item.price_in_cents * quantity
    end.reduce(:+)
  end

  def total_price_in_dollars
    total_price_in_cents / 100.to_f
  end

  def date
    created_at.strftime("%e %b %Y")
  end

  def items_and_quantities
    items.reduce(Hash.new(0)) do |hash, item|
      hash[item] += 1
      hash
    end
  end

  def status_name
    status.name.capitalize
  end

  def completed_or_cancelled?
    status.name == "completed" || status.name == "cancelled"
  end

  def display_submitted_at
    display_date_time(created_at)
  end

  def display_updated_at
    display_date_time(updated_at)
  end

  def set_total
    self.total_price_in_cents = calculated_price_in_cents
  end

  def display_date_time(date_time)
    date_time.strftime('%e %b %Y at %l:%M %p')
  end
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController

  def show
    @order = order(params[:id])
  end

  def update
    order = order(params["order_id"])
    order.status = status
    order.save
    redirect_to admin_dashboard_path
  end

end

app/controllers/customers/base_controller.rb
class Customers::BaseController < ApplicationController
  before_action :require_customer

  def require_customer
    render file: "/public/404" unless current_customer?
  end

end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < Customers::BaseController
  before_action :customer_orders
  include ApplicationHelper

  def customer_orders
    current_customer.orders
  end

  def index
    @status_filter = params[:status_filter]
    @statuses = Status.all.sort_by_name

    if valid_status_filter?
      @orders = filter_orders
    else
      render file: "/public/404"
    end
  end

  def show
    @order = order
    if customer_orders.include?(@order)
      render :show
    else
      render file: "/public/404"
    end
  end

  private

  def valid_status_filter?
    status_names = @statuses.pluck(:name)
    @status_filter.nil? || status_names.include?(@status_filter)
  end

  def filter_orders
    if @status_filter.nil?
      @orders = customer_orders.most_recent
    else
      status = status(@status_filter)
      @orders = customer_orders.where(status: status).most_recent
    end
  end

end

app/controllers/customers/sessions_controller.rb
class Customers::SessionsController < Customers::BaseController
  include MessageHelper

  skip_before_action :require_customer

  def new; end

  def create
    if authenticated_customer?
      set_customer_session
      flash_message_successful_login
      redirect_to dashboard_path
    else
      flash_message_failed_login
      render :new
    end
  end

  def destroy
    reset_session
    flash_message_successful_logout
    redirect_to(login_path)
  end

  private

  def customer
    Customer.find_by(email: params[:email])
  end

  def set_customer_session
    session[:customer_id] = customer.id
    session[:admin_id] = nil
  end

  def authenticated_customer?
    customer && customer.authenticate(params[:password])
  end
end

app/controllers/customers_controller.rb
class CustomersController < Customers::BaseController
  skip_before_action :require_customer, only: [:new, :create]

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      session[:customer_id] = @customer.id
      flash_message_successful_login
      redirect_to_correct_path
    else
      @errors = @customer.errors
      render :new
    end
  end

  def redirect_to_correct_path
    if @cart.contents.empty?
      redirect_to dashboard_path
    else
      redirect_to cart_path
    end
  end

  def dashboard; end

  private

  def customer_params
    params.require(:customer).permit(:first_name,
                                     :last_name,
                                     :email,
                                     :password,
                                     :password_confirmation)
  end
end

app/views/customers/orders/_orders.html.erb
<div class="list-group">
  <% @orders.each do |order| %>
    <%= link_to order_path(order_id: order.id), id: "order_#{order.id}", class: "list-group-item" do %>
      <strong>Order Total:</strong> <%= number_to_currency(order.total_price_in_dollars) %>
      <strong>Date:</strong> <%= order.date %>
      <strong>Status:</strong>
      <span class="status_<%= order.status_name.downcase %>">
        <%= order.status.name.capitalize %>
      </span>
    <% end %>
  <% end %>
</div>

app/views/customers/orders/index.html.erb
<div class="wrapper">
  <h1>Order history</h1>
  
  <% if @orders.any? %>
    <%= render partial: 'orders' %>
  <% else %>
    <p>You have not placed any orders.</p>
  <% end %>
</div>

app/views/customers/orders/show.html.erb
<div class="wrapper">
  <h2>Order from <%= @order.date %></h2>

  <div class="list-group">
    <div class="list-group-item">
      <h3 class="list-group-item-heading">Total: <%= number_to_currency(@order.total_price_in_dollars) %></h3>
    </div>
    <div class="list-group-item">
      <h3 class="list-group-item-heading status_<%= @order.status_name.downcase %>">Status: <%= @order.status_name %></h3>
      <p class="list-group-item-text">submitted at: <%= @order.display_submitted_at %></p>
      <% if @order.completed_or_cancelled? %>
        <%= render partial: 'shared/completed_or_cancelled' %>
      <% end %>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <td>Item</td>
        <td>Quantity x Price</td>
        <td>Subtotal</td>
      </tr>
    </thead>
    <tbody>
      <% @order.items_and_quantities.each do |item, quantity| %>
        <tr>
          <td><%= link_to item.title, item_path(item) %></td>
          <td><%= quantity %> x <%= number_to_currency(item.price_in_dollars) %></td>
          <td><%= number_to_currency(item.price_in_dollars(quantity)) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <hr />
  <h3 class="text-right">Total: <%= number_to_currency(@order.total_price_in_dollars) %></h3>
</div>