config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get '/login' => "customers/sessions#new"
  post '/login' => "customers/sessions#create"
  get '/dashboard' => "customers#dashboard"
  delete '/logout' => "customers/sessions#destroy", as: 'logout'
  # get '/checkout' => "checkout#checkout"

  scope '/admin' do
    root to: 'admins#show'
    get '/orders/:id' => "admins/orders#show", as: 'admin_order'
    put '/orders' => "admins/orders#update"
    get '/login' => "admins/sessions#new", as: 'admin_login'
    post '/login' => "admins/sessions#create"
    delete '/logout' => "admins/sessions#destroy", as: 'admin_logout'
    get '/dashboard' => "admins#show", as: 'admin_dashboard'
    get '/items' => "admins/items#index", as: 'admin_items'
    get '/items/:id/edit' => 'admins/items#edit', as: 'edit_admin_item'
  end
  resources :admins, only: [:edit, :update]

  resources :customers, only: [:new, :create]

  resources :items, only: [:index, :show]

  patch '/items/:id' => 'admins/items#update'
  get '/cart' => "carts#show", as: "cart"
  post '/cart' => "carts#update"
  delete '/cart' => "carts#destroy"

  get '/orders' => "customers/orders#index", as: 'customer_orders'
  get '/order' => "customers/orders#show"

  resources :checkouts do
    root to: 'checkouts#checkout'
  end
  resources :categories, :path => '', only: [:show]

  resources :carts, only: [:create]

end

app/views/shared/_completed_or_cancelled.html.erb
<p class="list-group-item-text"><%= @order.status_name.downcase %> at: <%= @order.display_updated_at %></p>

app/views/shared/_errors.html.erb
<% if @errors %>
  <div class="container alert alert-danger">
    <h3><%= pluralize(@errors.count, 'error') %> prevented this record from being saved.</h3>
    <ul>
      <% @errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_item.html.erb
<div id="item_<%= item.id %>" class="thumbnail">
  <%= link_to item_path(item) do %>
    <img src=<%= item.image_url %> alt=<%= item.title %>/>
    <div class="caption">
      <h3><%= item.title %></h3>
    </div>
  <% end %>
  <p><%= number_to_currency(item.price_in_dollars) %></p>
  <% if item.retired == false %>
    <%= button_to "Add to cart", carts_path(item_id: item.id), class:"btn btn-info add_to_cart" %>
  <% else %>
    <div class="button-disabled">
      Item not available
    </div>
  <% end %>
  <% if current_admin?  %>
    <%= link_to "Edit item", edit_admin_item_path(id: item.id), class: "btn btn-info" %>
  <% end %>
</div>

app/views/shared/_items.html.erb
<div class="container-fluid">
<% @items.each_slice(4) do |four_items| %>
  <div class="row">
    <% four_items.each_slice(2) do |two_items| %>
      <div class="col-md-6">
        <div class="row">
          <% two_items.each do |item| %>
            <div class="col-sm-6">
              <%= render partial: 'shared/item', locals: {item: item} %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/shared/_notices.html.erb
<% flash.each do |name, message| %>
  <div class="alert alert-<%= name %>">
    <div class="container">
      <%= content_tag :div, sanitize(message) %>
    </div>
  </div>
<% end %>

app/views/shared/_orders.html.erb
<div class="table-responsive">
  <table class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th> Order ID </th>
        <% if current_admin? %>
          <th> Customer ID </th>
          <th> Customer Name </th>
          <th> Customer Email </th>
        <% end %>
        <th> Order Total </th>
        <th> Order Date </th>
        <% if current_admin? %>
          <th class="dropdown">
             <a href="#" data-toggle="dropdown" class="dropdown-toggle">Order Status <b class="caret"></b></a>
             <ul class="dropdown-menu">
               <% if @status_filter %>
                  <li> <%= link_to "Clear filter", admin_dashboard_path(status_filter: nil), class: "dropdown-option" %>
                  <li role="separator" class="divider"></li>
               <% end %>
               <% @statuses.each do |status| %>
                  <li> <%= link_to "#{status.name.capitalize}", admin_dashboard_path(status_filter: status.name), class: "dropdown-option" %> </li>
               <% end %>
             </ul>
          </th>
        <% else %>
          <th class="dropdown">
             <a href="#" data-toggle="dropdown" class="dropdown-toggle">Order Status <b class="caret"></b></a>
             <ul class="dropdown-menu">
               <% if @status_filter %>
                  <li> <%= link_to "Clear filter", orders_path(status_filter: nil), class: "dropdown-option" %>
                  <li role="separator" class="divider"></li>
               <% end %>
               <% @statuses.each do |status| %>
                  <li> <%= link_to "#{status.name.capitalize}", orders_path(status_filter: status.name), class: "dropdown-option" %> </li>
               <% end %>
             </ul>
          </th>
        <% end %>
        <% if current_admin? %>
          <th> Mark as completed </th>
          <th> Mark as paid </th>
          <th> Cancel </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
      <tr class= "order_<%= order.id %>_row">
        <td> <%= link_to "#{order.id}", admin_order_path(order), class: "order_#{order.id}" %> </td>
        <% if current_admin? %>
          <td> <%= order.customer.id %> </td>
          <td> <%= order.customer.full_name %> </td>
          <td> <%= order.customer.email %> </td>
        <% end %>
        <td> <%= number_to_currency(order.total_price_in_dollars) %> </td>
        <td> <%= order.date %> </td>
        <td>
          <span class="status_<%= order.status_name.downcase %>">
            <%= order.status.name.capitalize %>
          </span>
        </td>
        <% if current_admin? %>
        <td>
          <% if order.status.paid? %>
            <%= button_to "Mark as completed", orders_path, method: :put, class: "order_#{order.id}_complete", params: {"order_id" => order.id, "status" => "completed"} %>
          <% end %>
        </td>
        <td>
          <% if order.status.name == "ordered" %>
            <%= button_to "Mark as paid", orders_path, method: :put, class: "order_#{order.id}_mark_as_paid", params: {"order_id" => order.id, "status" => "paid"} %>
          <% end %>
        </td>
        <td>
          <% if order.status.paid? || order.status.ordered? %>
            <%= button_to "Cancel", orders_path, method: :put, class: "order_#{order.id}_cancel", params: {"order_id" => order.id, "status" => "cancelled"} %>
          <% end %>
        </td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>