config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get '/login' => "customers/sessions#new"
  post '/login' => "customers/sessions#create"
  get '/dashboard' => "customers#dashboard"
  delete '/logout' => "customers/sessions#destroy", as: 'logout'
  # get '/checkout' => "checkout#checkout"

  scope '/admin' do
    root to: 'admins#show'
    get '/orders/:id' => "admins/orders#show", as: 'admin_order'
    put '/orders' => "admins/orders#update"
    get '/login' => "admins/sessions#new", as: 'admin_login'
    post '/login' => "admins/sessions#create"
    delete '/logout' => "admins/sessions#destroy", as: 'admin_logout'
    get '/dashboard' => "admins#show", as: 'admin_dashboard'
    get '/items' => "admins/items#index", as: 'admin_items'
    get '/items/:id/edit' => 'admins/items#edit', as: 'edit_admin_item'
  end
  resources :admins, only: [:edit, :update]

  resources :customers, only: [:new, :create]

  resources :items, only: [:index, :show]

  patch '/items/:id' => 'admins/items#update'
  get '/cart' => "carts#show", as: "cart"
  post '/cart' => "carts#update"
  delete '/cart' => "carts#destroy"

  get '/orders' => "customers/orders#index", as: 'customer_orders'
  get '/order' => "customers/orders#show"

  resources :checkouts do
    root to: 'checkouts#checkout'
  end
  resources :categories, :path => '', only: [:show]

  resources :carts, only: [:create]

end

app/models/cart.rb
class Cart
  include ApplicationHelper

  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || {}
  end

  def number_of_items
    contents.values.sum
  end

  def add_item(item_id)
    contents[item_id.to_s] ||= 0
    contents[item_id.to_s] += 1
  end

  def items
    items_with_quantities.reduce(Array.new) do |collector, (item, quantity)|
      quantity.times { collector << item }
      collector
    end
  end

  def items_with_quantities
    contents.reduce({}) do |memo, (id, quantity)|
      memo[item(id)] = quantity
      memo
    end
  end

  def total_price_in_dollars
    total_price_in_cents / 100.to_f
  end

  def empty?
    contents.empty?
  end

  def decrease_item_quantity(item_id)
    contents[item_id.to_s] -= 1
    clean_cart
  end

  def delete_entire_item(item_id)
    contents.delete(item_id.to_s)
  end

  def total_price_in_cents
    price_and_quantity.reduce(0) do |memo, prices|
      memo += prices[0] * prices[1]
      memo
    end
  end

  private

  def clean_cart
    contents.delete_if do |item_id, quantity|
      quantity == 0
    end
  end

  def price_and_quantity
    contents.map do |id, quantity|
      [item(id).price_in_cents, quantity]
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def create
    add_item_to_cart
    set_cart_session
    flash_message_add_item_to_cart(item)
    redirect_to items_path
  end

  def show; end

  def destroy
    if params[:remove].nil?
      @cart.decrease_item_quantity(item.id)
      last_item
    else
      @cart.delete_entire_item(item.id)
      flash_message_remove_from_cart(item)
    end
    set_cart_session
    redirect_to cart_path
  end

  def last_item
    contents = @cart.contents[item.id]
    flash_message_remove_from_cart(item) if contents.nil?
  end

  def update
    add_item_to_cart
    redirect_to cart_path
  end

  private

  def set_cart_session
    session[:cart] = @cart.contents
  end

  def add_item_to_cart
    @cart.add_item(item.id)
  end
end

app/views/carts/_cart.html.erb
<% @cart.items_with_quantities.each do |item, quantity| %>
  <div class="row">
    <div class="col-md-offset-2 col-md-2">
      <div class="thumbnail">
        <%= image_tag(item.image_url, alt: item.title) %>
      </div>
    </div>
    <div class="col-md-4" id="item_<%= item.id %>">
      <p><%= item.title %></p>
      <p><%= item.description %></p>
      <p><%= quantity %> x <%= number_to_currency(item.price_in_dollars) %>
      <%= link_to "-", cart_path(item_id: item.id), method: :delete, class: "minus" %>
      <%= link_to "+", cart_path(item_id: item.id), method: :post, class: "plus"%></p>
    <%= link_to "Remove", cart_path(item_id: item.id, :remove => "remove"), method: :delete, class: "button-delete" %>
  </div>
</div>
<% end %>
<div class="row">
  <div class="col-md-offset-2 col-md-2">
    <h3>Subtotal:</h3>
  </div>
  <div class="col-md-4">
    <h3 class="text-right"><%= number_to_currency(@cart.total_price_in_dollars) %></h3>
    <% if current_customer? %>
      <h3 class="text-right">
        <%= link_to "Checkout", new_checkout_path, class: "button" %>
      </h3>
    <% else %>
      <p class="text-right"><%= link_to "Login", login_path, class: "button-login" %></p>
      <p class="text-right">Create Account to Checkout <%= link_to "Register", new_customer_path(:from_cart => "from_cart"), class: "button-account" %></p>
    <% end %>
  </div>
</div>

app/views/carts/_empty_cart.html.erb
<h3>"Your cart is currently empty."</h3>
<%= link_to "Go Shopping", items_path, class: "btn btn-primary" %>

app/views/carts/show.html.erb
<div class="wrapper">
  <% if @cart.empty? %>
    <%= render partial: "empty_cart" %>
  <% else %>
    <%= render partial: "cart" %>
  <% end %>
</div>