config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get '/login' => "customers/sessions#new"
  post '/login' => "customers/sessions#create"
  get '/dashboard' => "customers#dashboard"
  delete '/logout' => "customers/sessions#destroy", as: 'logout'
  # get '/checkout' => "checkout#checkout"

  scope '/admin' do
    root to: 'admins#show'
    get '/orders/:id' => "admins/orders#show", as: 'admin_order'
    put '/orders' => "admins/orders#update"
    get '/login' => "admins/sessions#new", as: 'admin_login'
    post '/login' => "admins/sessions#create"
    delete '/logout' => "admins/sessions#destroy", as: 'admin_logout'
    get '/dashboard' => "admins#show", as: 'admin_dashboard'
    get '/items' => "admins/items#index", as: 'admin_items'
    get '/items/:id/edit' => 'admins/items#edit', as: 'edit_admin_item'
  end
  resources :admins, only: [:edit, :update]

  resources :customers, only: [:new, :create]

  resources :items, only: [:index, :show]

  patch '/items/:id' => 'admins/items#update'
  get '/cart' => "carts#show", as: "cart"
  post '/cart' => "carts#update"
  delete '/cart' => "carts#destroy"

  get '/orders' => "customers/orders#index", as: 'customer_orders'
  get '/order' => "customers/orders#show"

  resources :checkouts do
    root to: 'checkouts#checkout'
  end
  resources :categories, :path => '', only: [:show]

  resources :carts, only: [:create]

end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :price_in_cents, presence: true
  validates :image_url, presence: true
  validates_uniqueness_of :title
  validates :retired, inclusion: { in: [true, false] }

  belongs_to :category
  has_many :order_items
  has_many :orders, through: :order_items

  def price_in_dollars(quantity = 1)
    quantity * price_in_cents / 100.to_f
  end

  def category_name
    category.name
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < Admins::BaseController

  def index
    @items = Item.all
  end

  def edit
    @item = item(params[:id])
  end

  def update
    @item = item(params[:id])
    if @item.update(item_params)
      flash_message_successful_update
      redirect_to item_path(@item)
    else
      flash_message_failed_update
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:title, :description, :image_url, :retired)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def show
    @item = item(params[:id])
  end
end

app/views/items/edit.html.erb
<h1>Edit item</h1>

<%= bootstrap_form_for(@item)do |f| %>
  <%= f.text_field :title, placeholder: "Title" %>
  <%= f.text_area :description, placeholder: "Description" %>
  <%= f.text_field :image_url, placeholder: "Image" %>
  <%= f.select :retired, ["True","False"], placeholder: "#{@item.retired}" %>
  <%= f.submit "Update", class: "btn btn-success btn-block" %>
<% end %>

app/views/items/index.html.erb
<div class="wrapper">
  <h1 class="text-center">All wooden goods</h1>
  <hr class="divider" />
  <%= render partial: 'shared/items' %>
</div>

app/views/items/show.html.erb
<div class="wrapper">
  <div class="row">
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src=<%= @item.image_url %> alt=<%= @item.title %>>
      </div>
    </div>
    <div class="col-sm-6 col-md-8">
      <p><%= link_to @item.category_name, category_path(@item.category) %></p>
      <h2><%= @item.title %></h2>
      <p><%= @item.description %></p>
      <div>
        <h4><%= number_to_currency(@item.price_in_dollars) %></h4>
        <% if @item.retired == false %>
          <%= button_to "Add to cart", carts_path(item_id: @item.id), class:"btn btn-info add_to_cart" %>
        <% else %>
          <div class="button-disabled">
            Item not available
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>